// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CAB_cpp_bitwise
NumericVector CAB_cpp_bitwise(int pop_size, NumericMatrix parents, double bias);
RcppExport SEXP CAB_CAB_cpp_bitwise(SEXP pop_sizeSEXP, SEXP parentsSEXP, SEXP biasSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type pop_size(pop_sizeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type parents(parentsSEXP);
    Rcpp::traits::input_parameter< double >::type bias(biasSEXP);
    __result = Rcpp::wrap(CAB_cpp_bitwise(pop_size, parents, bias));
    return __result;
END_RCPP
}
// CAB_cpp_compute__I_xy_I__formal_event_record
NumericVector CAB_cpp_compute__I_xy_I__formal_event_record(DataFrame data, CharacterVector x_event, CharacterVector y_event, CharacterVector break_event);
RcppExport SEXP CAB_CAB_cpp_compute__I_xy_I__formal_event_record(SEXP dataSEXP, SEXP x_eventSEXP, SEXP y_eventSEXP, SEXP break_eventSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type x_event(x_eventSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y_event(y_eventSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type break_event(break_eventSEXP);
    __result = Rcpp::wrap(CAB_cpp_compute__I_xy_I__formal_event_record(data, x_event, y_event, break_event));
    return __result;
END_RCPP
}
// CAB_cpp_diff
NumericVector CAB_cpp_diff(NumericVector x);
RcppExport SEXP CAB_CAB_cpp_diff(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(CAB_cpp_diff(x));
    return __result;
END_RCPP
}
// CAB_cpp_srswo
NumericMatrix CAB_cpp_srswo(int size, int group_size, int n);
RcppExport SEXP CAB_CAB_cpp_srswo(SEXP sizeSEXP, SEXP group_sizeSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< int >::type group_size(group_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(CAB_cpp_srswo(size, group_size, n));
    return __result;
END_RCPP
}
// CAB_cpp_srswo2
NumericMatrix CAB_cpp_srswo2(int size, int n);
RcppExport SEXP CAB_CAB_cpp_srswo2(SEXP sizeSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(CAB_cpp_srswo2(size, n));
    return __result;
END_RCPP
}
// timesTwo
NumericVector timesTwo(NumericVector x);
RcppExport SEXP CAB_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(timesTwo(x));
    return __result;
END_RCPP
}
