# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CAB_cpp_bitwise <- function(pop_size, fathers, mothers, bias) {
    .Call('CAB_CAB_cpp_bitwise', PACKAGE = 'CAB', pop_size, fathers, mothers, bias)
}

CAB_cpp_clean_short_ixyi <- function(data, x_name, y_name, gap) {
    .Call('CAB_CAB_cpp_clean_short_ixyi', PACKAGE = 'CAB', data, x_name, y_name, gap)
}

CAB_cpp_clean_short_ixxi <- function(data, x_name, gap) {
    .Call('CAB_CAB_cpp_clean_short_ixxi', PACKAGE = 'CAB', data, x_name, gap)
}

CAB_cpp_compute__I_xy_I__formal_event_record <- function(data, x_event, y_event, break_event) {
    .Call('CAB_CAB_cpp_compute__I_xy_I__formal_event_record', PACKAGE = 'CAB', data, x_event, y_event, break_event)
}

CAB_cpp_diff <- function(x) {
    .Call('CAB_CAB_cpp_diff', PACKAGE = 'CAB', x)
}

CAB_cpp_geometric_fitness_selection <- function(fitness, pop_size, p) {
    .Call('CAB_CAB_cpp_geometric_fitness_selection', PACKAGE = 'CAB', fitness, pop_size, p)
}

CAB_cpp_indicator_matrix <- function(x) {
    .Call('CAB_CAB_cpp_indicator_matrix', PACKAGE = 'CAB', x)
}

CAB_cpp_int2bin <- function(bits, n) {
    .Call('CAB_CAB_cpp_int2bin', PACKAGE = 'CAB', bits, n)
}

CAB_ks <- function(sample_1, sample_2) {
    .Call('CAB_CAB_ks', PACKAGE = 'CAB', sample_1, sample_2)
}

CAB_cpp_local_times_formal_event_record <- function(data, event, marker, event_offset, n_markers) {
    .Call('CAB_CAB_cpp_local_times_formal_event_record', PACKAGE = 'CAB', data, event, marker, event_offset, n_markers)
}

CAB_cpp_local_binning <- function(local_times, visit_lengths, max_bin, bin_resolution) {
    .Call('CAB_CAB_cpp_local_binning', PACKAGE = 'CAB', local_times, visit_lengths, max_bin, bin_resolution)
}

CAB_cpp_local_times_ragged_event_record <- function(event_times, marker_times, event_offset) {
    .Call('CAB_CAB_cpp_local_times_ragged_event_record', PACKAGE = 'CAB', event_times, marker_times, event_offset)
}

CAB_cpp_not_duplicated <- function(x) {
    .Call('CAB_CAB_cpp_not_duplicated', PACKAGE = 'CAB', x)
}

CAB_cpp_srswo <- function(size, group_size, n) {
    .Call('CAB_CAB_cpp_srswo', PACKAGE = 'CAB', size, group_size, n)
}

CAB_cpp_srswo2 <- function(size, n) {
    .Call('CAB_CAB_cpp_srswo2', PACKAGE = 'CAB', size, n)
}

CAB_cpp_unique <- function(x) {
    .Call('CAB_CAB_cpp_unique', PACKAGE = 'CAB', x)
}

timesTwo <- function(x) {
    .Call('CAB_timesTwo', PACKAGE = 'CAB', x)
}

