# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CAB_cpp_bitwise <- function(pop_size, parents, bias) {
    .Call('CAB_CAB_cpp_bitwise', PACKAGE = 'CAB', pop_size, parents, bias)
}

timesTwo <- function(x) {
    .Call('CAB_timesTwo', PACKAGE = 'CAB', x)
}

