# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CAB_cpp_bitwise_sampler <- function(pop_size, parents) {
    .Call('CAB_CAB_cpp_bitwise_sampler', PACKAGE = 'CAB', pop_size, parents)
}

timesTwo <- function(x) {
    .Call('CAB_timesTwo', PACKAGE = 'CAB', x)
}

